---

- hosts: localhost
  connection: local

  vars:
    working_dir: "{{ playbook_dir }}/generated"

  pre_tasks:

    - name: Deletes working directory
      file: path="{{ working_dir }}" state=absent

    - name: Creates working directory
      file: path="{{ working_dir }}" state=directory

  roles:
    - vagrant-virtual-machines